# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo

  backend:
    image: buildkite/puppeteer:5.2.1
    restart: always
    working_dir: /backend/
    environment:
      - NODE_ENV=development
    ports:
      - 3030:3030
    volumes:
      - ./backend/:/backend/
    command: bash -c "npm install && npm start"
    depends_on:
      - mongo

  frontend:
    image: node:15.4.0
    restart: always
    working_dir: /frontend/
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/frontend/
    command: bash -c "npm install && npm start"
    depends_on:
      - backend
